INSTALL_TARGET:=install
UNINSTALL_TARGET:=uninstall
INSTALL_PREFIX:=$(INSTALL_TARGET)-
UNINSTALL_PREFIX:=$(UNINSTALL_TARGET)-

STOW:=stow
INSTALL:=$(STOW)
UNINSTALL:=$(STOW) --delete

DIRS:=$(wildcard */)
TARGETS:=$(DIRS:/=)

all : $(INSTALL_TARGET)
clean : $(UNINSTALL_TARGET)

$(INSTALL_TARGET) : $(addprefix $(INSTALL_PREFIX),$(TARGETS))
$(UNINSTALL_TARGET) : $(addprefix $(UNINSTALL_PREFIX),$(TARGETS))

$(INSTALL_PREFIX)% : %
	$(INSTALL) '$<'

$(UNINSTALL_PREFIX)% : %
	$(UNINSTALL) '$<'
